# main text of home
name: Madison Bell
bio: Berlin-based product manager, burner, fitness enthusisast and aspiring seamstress

# twitter summary info
description: Madison Bell | Product Manager

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/madison-bell-square.jpg

url: http://www.madibell.com
# your url: http://USERNAME.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'


# if you don't have any of social below, comment the line
facebook: madibell
# twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: madisonbell
#youtube: myyoutube
#spotify: myspotify
github: madibell
#stackoverflow: stackoverflow
#quora: userquora
#reddit: username
#medium: medium
#vimeo: myvimeo
#email: email

# do you want some animations?
animation: false

sass:
    sass_dir: _sass
    style: :compressed

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
